### ISSUE TITLE
Unbreak examples after glutin update

### ISSUE THREAD

**Issue by est31** [glium/glium#1758]
Some examples were broken by #1757, they should be fixed. This is a blocker for the 0.26.0 release.

- [x] Tutorial examples (https://github.com/glium/glium/pull/1765)
- [ ] deferred: needs various ownership changes. (#1771)
- [x] fullscreen: needs access to EventLoopWindowTarget, which is not passed in by the current `start_loop`. (#1770)
- [x] screenshot-asynchronous: uses a `loop` for game loop, instead of `start_loop` (#1769)
- [x] shadow_mapping: uses a `loop` for game loop, instead of `start_loop` (#1769)

**Comment by est31** [comment]
@KeyMaster- want to have a look?

**Comment by KeyMaster-** [comment]
I won't have time for it today, but maybe in the next few days.
As I mentioned, the way the game loop gets run needs to change completely, and I'm not sure what the preferred way of doing it would be, so I wouldn't know how to progress on that immediately.

**Comment by est31** [comment]
@KeyMaster- thanks for helping out! Doing it in the next few days is fine :). I just wanted the alpha release out quickly so that people can experiment with it. The 0.26.0 release is not very urgent. In fact, glutin doesn't have a proper 0.22.0 release yet either (that would be the second blocker for 0.26.0).

**Comment by est31** [comment]
@KeyMaster- just a heads up I've filed a PR to address the problem for the tutorials here: #1765

**Comment by sam0x17** [comment]
Just out of curiosity what changed might I need to make to fix the instancing example and/or is there an older version I can use that doesn't haven this issue?

**Comment by est31** [comment]
@sam0x17 the `instancing` example works for me. Do you mean `displacement_mapping`? I went back to commits b1e5928befb0a09e66c9b6f7d9c07a2c0d87b8ad and 57e4dbc678d5de01144608866ca4b6ce63690406, and couldn't get it to work.

You can see which examples work and which doesn't in this commit: https://github.com/KeyMaster-/glium/commit/84f82d3098fbc75aa22160b47bf0a2bdada01f07

**Comment by sam0x17** [comment]
@est31 I am trying to run the instancing example in a new project, so maybe that is my issue. I copied the code for `instancing.rs` into `main.rs`, added `glium` to my `Cargo.toml` file, copy pasted the support module into my `src` folder, and get a bunch of errors:

Cargo.toml:
```
[dependencies]
glium = "*"
genmesh = "0.6"
obj = { version = "0.9", features = ["genmesh"] }
rand = "0.7"
glutin = "0.22.0-alpha1"
```

src/main.rs: (same as glium/examples/instances.rs)
src/support: (same as glium/examples/support)


Errors:

```
$ cargo run
   Compiling instances v0.1.0 (/home/sam/workspace/instances)
error[E0432]: unresolved import `glium::glutin::event_loop`
 --> src/support/mod.rs:9:20
  |
9 | use glium::glutin::event_loop::{EventLoop, ControlFlow};
  |                    ^^^^^^^^^^ could not find `event_loop` in `glutin`

error[E0432]: unresolved import `glium::glutin::event`
  --> src/support/mod.rs:10:20
   |
10 | use glium::glutin::event::{Event, StartCause};
   |                    ^^^^^ could not find `event` in `glutin`

error[E0433]: failed to resolve: could not find `event_loop` in `glutin`
  --> src/main.rs:17:30
   |
17 |     let event_loop = glutin::event_loop::EventLoop::new();
   |                              ^^^^^^^^^^ could not find `event_loop` in `glutin`

error[E0433]: failed to resolve: could not find `window` in `glutin`
  --> src/main.rs:18:22
   |
18 |     let wb = glutin::window::WindowBuilder::new();
   |                      ^^^^^^ could not find `window` in `glutin`

error[E0433]: failed to resolve: could not find `event` in `glutin`
   --> src/main.rs:124:25
    |
124 |                 glutin::event::Event::WindowEvent { event, .. } => match event {
    |                         ^^^^^ could not find `event` in `glutin`

error[E0433]: failed to resolve: could not find `event` in `glutin`
   --> src/main.rs:125:29
    |
125 |                     glutin::event::WindowEvent::CloseRequested => action = support::Action::Stop,
    |                             ^^^^^ could not find `event` in `glutin`

error: aborting due to 6 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `instances`.

To learn more, run the command again with --verbose.
```

**Comment by est31** [comment]
@sam0x17 you took the code from git while using the last non-alpha release on crates.io. Try doing `glium = "0.26.0-alpha1"` in Cargo.toml instead.

**Comment by sam0x17** [comment]
@est31 I still get the following:

```
$ cargo run
   Compiling instances v0.1.0 (/home/sam/workspace/instances)
error[E0433]: failed to resolve: could not find `event` in `glutin`
   --> src/support/camera.rs:153:53
    |
153 |     pub fn process_input(&mut self, event: &glutin::event::WindowEvent) {
    |                                                     ^^^^^ could not find `event` in `glutin`

error[E0433]: failed to resolve: could not find `event` in `glutin`
   --> src/support/camera.rs:155:21
    |
155 |             glutin::event::WindowEvent::KeyboardInput { input, .. } => input,
    |                     ^^^^^ could not find `event` in `glutin`

error[E0433]: failed to resolve: could not find `event` in `glutin`
   --> src/support/camera.rs:158:46
    |
158 |         let pressed = input.state == glutin::event::ElementState::Pressed;
    |                                              ^^^^^ could not find `event` in `glutin`

error[E0433]: failed to resolve: could not find `event` in `glutin`
   --> src/support/camera.rs:164:21
    |
164 |             glutin::event::VirtualKeyCode::Up => self.moving_up = pressed,
    |                     ^^^^^ could not find `event` in `glutin`

error[E0433]: failed to resolve: could not find `event` in `glutin`
   --> src/support/camera.rs:165:21
    |
165 |             glutin::event::VirtualKeyCode::Down => self.moving_down = pressed,
    |                     ^^^^^ could not find `event` in `glutin`

error[E0433]: failed to resolve: could not find `event` in `glutin`
   --> src/support/camera.rs:166:21
    |
166 |             glutin::event::VirtualKeyCode::A => self.moving_left = pressed,
    |                     ^^^^^ could not find `event` in `glutin`

error[E0433]: failed to resolve: could not find `event` in `glutin`
   --> src/support/camera.rs:167:21
    |
167 |             glutin::event::VirtualKeyCode::D => self.moving_right = pressed,
    |                     ^^^^^ could not find `event` in `glutin`

error[E0433]: failed to resolve: could not find `event` in `glutin`
   --> src/support/camera.rs:168:21
    |
168 |             glutin::event::VirtualKeyCode::W => self.moving_forward = pressed,
    |                     ^^^^^ could not find `event` in `glutin`

error[E0433]: failed to resolve: could not find `event` in `glutin`
   --> src/support/camera.rs:169:21
    |
169 |             glutin::event::VirtualKeyCode::S => self.moving_backward = pressed,
    |                     ^^^^^ could not find `event` in `glutin`

error: aborting due to 9 previous errors

For more information about this error, try `rustc --explain E0433`.
error: Could not compile `instances`.

To learn more, run the command again with --verbose.
```

**Comment by sam0x17** [comment]
aha! I got it working by replacing `extern crate glutin` in `camera.rs` with `use glium::glutin;`

**Comment by est31** [comment]
@sam0x17 thanks. next time please file a separate issue.

**Comment by sam0x17** [comment]
will do!
